//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:01 PM BRST 
//


package br.gov.model.generico2015;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContaCorrenteBancaria_t", propOrder = {
    "banco",
    "agencia",
    "dvAgencia",
    "contaCorrente",
    "dvContaCorrente"
})
public class ContaCorrenteBancariaT {

    @XmlElement(name = "Banco", required = true)
    protected String banco;
    @XmlElement(name = "Agencia", required = true)
    protected String agencia;
    @XmlElement(name = "DVAgencia")
    protected String dvAgencia;
    @XmlElement(name = "ContaCorrente", required = true)
    protected String contaCorrente;
    @XmlElement(name = "DVContaCorrente")
    protected String dvContaCorrente;

     
    public String getBanco() {
        return banco;
    }

     
    public void setBanco(String value) {
        this.banco = value;
    }

     
    public String getAgencia() {
        return agencia;
    }

     
    public void setAgencia(String value) {
        this.agencia = value;
    }

     
    public String getDVAgencia() {
        return dvAgencia;
    }

     
    public void setDVAgencia(String value) {
        this.dvAgencia = value;
    }

     
    public String getContaCorrente() {
        return contaCorrente;
    }

     
    public void setContaCorrente(String value) {
        this.contaCorrente = value;
    }

     
    public String getDVContaCorrente() {
        return dvContaCorrente;
    }

     
    public void setDVContaCorrente(String value) {
        this.dvContaCorrente = value;
    }

}
