//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:01 PM BRST 
//


package br.gov.model.generico2015;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


 
@XmlType(name = "DeclaracaoNegativa_t")
@XmlEnum
public enum DeclaracaoNegativaT {

    @XmlEnumValue("Nenhum dado a declarar")
    NENHUM_DADO_A_DECLARAR("Nenhum dado a declarar");
    private final String value;

    DeclaracaoNegativaT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeclaracaoNegativaT fromValue(String v) {
        for (DeclaracaoNegativaT c: DeclaracaoNegativaT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
