//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:01 PM BRST 
//


package br.gov.model.generico2015;

import javax.xml.bind.annotation.XmlRegistry;


 
@XmlRegistry
public class ObjectFactory {


     
    public ObjectFactory() {
    }

     
    public LegislacaoMunicipalT createLegislacaoMunicipalT() {
        return new LegislacaoMunicipalT();
    }

     
    public NumeroEmpenhoT createNumeroEmpenhoT() {
        return new NumeroEmpenhoT();
    }

     
    public LegislacaoT createLegislacaoT() {
        return new LegislacaoT();
    }

     
    public DescritorContabil14T createDescritorContabil14T() {
        return new DescritorContabil14T();
    }

     
    public PISPASEPComAtributoT createPISPASEPComAtributoT() {
        return new PISPASEPComAtributoT();
    }

     
    public DescritorConciliacoesBancariasT createDescritorConciliacoesBancariasT() {
        return new DescritorConciliacoesBancariasT();
    }

     
    public ContaCorrenteBancariaT createContaCorrenteBancariaT() {
        return new ContaCorrenteBancariaT();
    }

     
    public DescritorMensalT createDescritorMensalT() {
        return new DescritorMensalT();
    }

     
    public CPFComAtributoT createCPFComAtributoT() {
        return new CPFComAtributoT();
    }

     
    public IdentificacaoIndividualT createIdentificacaoIndividualT() {
        return new IdentificacaoIndividualT();
    }

     
    public RGComAtributoT createRGComAtributoT() {
        return new RGComAtributoT();
    }

     
    public TelefoneT createTelefoneT() {
        return new TelefoneT();
    }

     
    public IdentificacaoInscricaoGenericaT createIdentificacaoInscricaoGenericaT() {
        return new IdentificacaoInscricaoGenericaT();
    }

     
    public LegislacaoMunicipalComDatasT createLegislacaoMunicipalComDatasT() {
        return new LegislacaoMunicipalComDatasT();
    }

     
    public DescritorContabil13T createDescritorContabil13T() {
        return new DescritorContabil13T();
    }

     
    public DescritorPlanejamentoAtualizacaoT createDescritorPlanejamentoAtualizacaoT() {
        return new DescritorPlanejamentoAtualizacaoT();
    }

     
    public EntidadeOrcamentariaT createEntidadeOrcamentariaT() {
        return new EntidadeOrcamentariaT();
    }

     
    public DescritorT createDescritorT() {
        return new DescritorT();
    }

     
    public DescritorQuadrimestreT createDescritorQuadrimestreT() {
        return new DescritorQuadrimestreT();
    }

     
    public IdentificacaoEspecialT createIdentificacaoEspecialT() {
        return new IdentificacaoEspecialT();
    }

     
    public IdentificacaoT createIdentificacaoT() {
        return new IdentificacaoT();
    }

     
    public TipoDocumentoIdentificacaoIndividualT createTipoDocumentoIdentificacaoIndividualT() {
        return new TipoDocumentoIdentificacaoIndividualT();
    }

     
    public DescritorPPAAtualizacaoT createDescritorPPAAtualizacaoT() {
        return new DescritorPPAAtualizacaoT();
    }

     
    public NumeroContratoT createNumeroContratoT() {
        return new NumeroContratoT();
    }

     
    public DespesaComLicitacaoT createDespesaComLicitacaoT() {
        return new DespesaComLicitacaoT();
    }

     
    public IdentificacaoPensionistaT createIdentificacaoPensionistaT() {
        return new IdentificacaoPensionistaT();
    }

     
    public DescritorContabilT createDescritorContabilT() {
        return new DescritorContabilT();
    }

     
    public PossuiAutorizacaoJudicialReceberAcimaTetoSimT createPossuiAutorizacaoJudicialReceberAcimaTetoSimT() {
        return new PossuiAutorizacaoJudicialReceberAcimaTetoSimT();
    }

     
    public CPFSemTipoT createCPFSemTipoT() {
        return new CPFSemTipoT();
    }

     
    public DescritorContasAnuaisT createDescritorContasAnuaisT() {
        return new DescritorContasAnuaisT();
    }

     
    public CertidaoNascimentoComAtributoT createCertidaoNascimentoComAtributoT() {
        return new CertidaoNascimentoComAtributoT();
    }

     
    public AcaoGovernoT createAcaoGovernoT() {
        return new AcaoGovernoT();
    }

     
    public DescritorPPAT createDescritorPPAT() {
        return new DescritorPPAT();
    }

     
    public IdentificacaoAgentePublicoT createIdentificacaoAgentePublicoT() {
        return new IdentificacaoAgentePublicoT();
    }

     
    public NumeroConvenioT createNumeroConvenioT() {
        return new NumeroConvenioT();
    }

     
    public CNPJT createCNPJT() {
        return new CNPJT();
    }

     
    public MunicipioEntidadeT createMunicipioEntidadeT() {
        return new MunicipioEntidadeT();
    }

     
    public EnderecoT createEnderecoT() {
        return new EnderecoT();
    }

     
    public DescritorPlanejamentoT createDescritorPlanejamentoT() {
        return new DescritorPlanejamentoT();
    }

     
    public CPFT createCPFT() {
        return new CPFT();
    }

}
