//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:01 PM BRST 
//


package br.gov.model.generico2015;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDocumentoIdentificacaoIndividual_t", namespace = "http://www.tce.sp.gov.br/audesp/xml/atospessoal", propOrder = {
    "cpf",
    "certidaoNascimentoComAtributoT",
    "pispasepComAtributoT",
    "rgComAtributoT"
})
public class TipoDocumentoIdentificacaoIndividualT {

    @XmlElement(name = "CPF")
    protected CPFComAtributoT cpf;
    @XmlElement(name = "CertidaoNascimento_ComAtributo_t")
    protected CertidaoNascimentoComAtributoT certidaoNascimentoComAtributoT;
    @XmlElement(name = "PIS_PASEP_ComAtributo_t")
    protected PISPASEPComAtributoT pispasepComAtributoT;
    @XmlElement(name = "RG_ComAtributo_t")
    protected RGComAtributoT rgComAtributoT;

     
    public CPFComAtributoT getCPF() {
        return cpf;
    }

     
    public void setCPF(CPFComAtributoT value) {
        this.cpf = value;
    }

     
    public CertidaoNascimentoComAtributoT getCertidaoNascimentoComAtributoT() {
        return certidaoNascimentoComAtributoT;
    }

     
    public void setCertidaoNascimentoComAtributoT(CertidaoNascimentoComAtributoT value) {
        this.certidaoNascimentoComAtributoT = value;
    }

     
    public PISPASEPComAtributoT getPISPASEPComAtributoT() {
        return pispasepComAtributoT;
    }

     
    public void setPISPASEPComAtributoT(PISPASEPComAtributoT value) {
        this.pispasepComAtributoT = value;
    }

     
    public RGComAtributoT getRGComAtributoT() {
        return rgComAtributoT;
    }

     
    public void setRGComAtributoT(RGComAtributoT value) {
        this.rgComAtributoT = value;
    }

}
