//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.08 at 05:17:26 PM BRST 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tce.sp.gov.br/audesp/xml/generico", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)


//package br.gov.verbasRemuneratorias.model;
//
//import javax.xml.bind.annotation.XmlSchema;

@XmlSchema(
    namespace="http://www.tce.sp.gov.br/audesp/xml/remuneracao", 
    elementFormDefault=javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
  xmlns ={
//		  @XmlNs(prefix="ap", namespaceURI= "http://www.tce.sp.gov.br/audesp/xml/atospessoais"),
//		  @XmlNs(prefix="aux", namespaceURI= "http://www.tce.sp.gov.br/audesp/xml/auxiliar"),
		  @XmlNs(prefix="cvr", namespaceURI= "http://www.tce.sp.gov.br/audesp/xml/remuneracao"),
		  @XmlNs(prefix="gen", namespaceURI= "http://www.tce.sp.gov.br/audesp/xml/generico")
		 
    })



package br.gov.model.verbasRemuneratorias;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;