//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 06:55:58 PM BRST 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tce.sp.gov.br/audesp/xml/generico", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//package br.gov.pagamento.model;
@XmlSchema(namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@XmlNs(prefix = "ap", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/atospessoal"),
		@XmlNs(prefix = "aux", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/auxiliar"),
		@XmlNs(prefix = "pfo", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/remuneracao"),
		@XmlNs(prefix = "gen", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/generico")

})

package br.gov.model.pagamento;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;
