//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 05:08:12 PM BRT 
//


package br.gov.model.pagamento;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PagamentoFolhaOrdinariaAgentePublico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PagamentoFolhaOrdinariaAgentePublico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Descritor" type="{http://www.tce.sp.gov.br/audesp/xml/generico}DescritorMensal_t"/>
 *         &lt;element name="AnoPagamento" type="{http://www.tce.sp.gov.br/audesp/xml/generico}Ano_t"/>
 *         &lt;element name="MesPagamento" type="{http://www.tce.sp.gov.br/audesp/xml/generico}Mes_t"/>
 *         &lt;element name="IdentificacaoAgentePublico" type="{http://www.tce.sp.gov.br/audesp/xml/remuneracao}IdentificacaoAgentePublico" maxOccurs="unbounded"/>
 *         &lt;element name="IdentificacaoPensionista" type="{http://www.tce.sp.gov.br/audesp/xml/remuneracao}IdentificacaoPensionista" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagamentoFolhaOrdinariaAgentePublico", namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", propOrder = {
    "descritor",
    "anoPagamento",
    "mesPagamento",
    "identificacaoAgentePublico",
    "identificacaoPensionista"
})

@XmlRootElement(name = "PagamentoFolhaOrdinariaAgentePublico")
public class PagamentoFolhaOrdinariaAgentePublico {

    @XmlElement(name = "Descritor", required = true)
    protected DescritorMensalT descritor;
    @XmlElement(name = "AnoPagamento")
    protected int anoPagamento;
    @XmlElement(name = "MesPagamento")
    protected int mesPagamento;
    @XmlElement(name = "IdentificacaoAgentePublico", required = true)
    protected List<IdentificacaoAgentePublico> identificacaoAgentePublico;
    @XmlElement(name = "IdentificacaoPensionista")
    protected List<IdentificacaoPensionista> identificacaoPensionista;

    /**
     * Gets the value of the descritor property.
     * 
     * @return
     *     possible object is
     *     {@link DescritorMensalT }
     *     
     */
    public DescritorMensalT getDescritor() {
        return descritor;
    }

    /**
     * Sets the value of the descritor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescritorMensalT }
     *     
     */
    public void setDescritor(DescritorMensalT value) {
        this.descritor = value;
    }

    /**
     * Gets the value of the anoPagamento property.
     * 
     */
    public int getAnoPagamento() {
        return anoPagamento;
    }

    /**
     * Sets the value of the anoPagamento property.
     * 
     */
    public void setAnoPagamento(int value) {
        this.anoPagamento = value;
    }

    /**
     * Gets the value of the mesPagamento property.
     * 
     */
    public int getMesPagamento() {
        return mesPagamento;
    }

    /**
     * Sets the value of the mesPagamento property.
     * 
     */
    public void setMesPagamento(int value) {
        this.mesPagamento = value;
    }

    /**
     * Gets the value of the identificacaoAgentePublico property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificacaoAgentePublico property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacaoAgentePublico().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificacaoAgentePublico }
     * 
     * 
     */
    public List<IdentificacaoAgentePublico> getIdentificacaoAgentePublico() {
        if (identificacaoAgentePublico == null) {
            identificacaoAgentePublico = new ArrayList<IdentificacaoAgentePublico>();
        }
        return this.identificacaoAgentePublico;
    }

    /**
     * Gets the value of the identificacaoPensionista property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificacaoPensionista property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacaoPensionista().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificacaoPensionista }
     * 
     * 
     */
    public List<IdentificacaoPensionista> getIdentificacaoPensionista() {
        if (identificacaoPensionista == null) {
            identificacaoPensionista = new ArrayList<IdentificacaoPensionista>();
        }
        return this.identificacaoPensionista;
    }

}
