//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 04:21:25 PM BRST 
//


package br.gov.model.resumoFolha;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResumoFolha", namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", propOrder = {
    "municipioEntidadeLotacao",
    "vlFGTS",
    "vlContribPrevGeralAgPolitico",
    "vlContribPrevProprioAgPolitico",
    "vlContribPrevGeralAgNaoPolitico",
    "vlContribPrevProprioAgNaoPolitico"
})
@XmlRootElement(name = "ResumoFolha")
public class ResumoFolhaT {

    @XmlElement(name = "MunicipioEntidadeLotacao", required = true)
    protected MunicipioEntidadeT municipioEntidadeLotacao;
    @XmlElement(name = "VlFGTS", required = true)
    protected BigDecimal vlFGTS;
    @XmlElement(name = "VlContribPrevGeralAgPolitico", required = true)
    protected BigDecimal vlContribPrevGeralAgPolitico;
    @XmlElement(name = "VlContribPrevProprioAgPolitico", required = true)
    protected BigDecimal vlContribPrevProprioAgPolitico;
    @XmlElement(name = "VlContribPrevGeralAgNaoPolitico", required = true)
    protected BigDecimal vlContribPrevGeralAgNaoPolitico;
    @XmlElement(name = "VlContribPrevProprioAgNaoPolitico", required = true)
    protected BigDecimal vlContribPrevProprioAgNaoPolitico;

     
    public MunicipioEntidadeT getMunicipioEntidadeLotacao() {
        return municipioEntidadeLotacao;
    }

     
    public void setMunicipioEntidadeLotacao(MunicipioEntidadeT value) {
        this.municipioEntidadeLotacao = value;
    }

     
    public BigDecimal getVlFGTS() {
        return vlFGTS;
    }

     
    public void setVlFGTS(BigDecimal value) {
        this.vlFGTS = value;
    }

     
    public BigDecimal getVlContribPrevGeralAgPolitico() {
        return vlContribPrevGeralAgPolitico;
    }

     
    public void setVlContribPrevGeralAgPolitico(BigDecimal value) {
        this.vlContribPrevGeralAgPolitico = value;
    }

     
    public BigDecimal getVlContribPrevProprioAgPolitico() {
        return vlContribPrevProprioAgPolitico;
    }

     
    public void setVlContribPrevProprioAgPolitico(BigDecimal value) {
        this.vlContribPrevProprioAgPolitico = value;
    }

     
    public BigDecimal getVlContribPrevGeralAgNaoPolitico() {
        return vlContribPrevGeralAgNaoPolitico;
    }

     
    public void setVlContribPrevGeralAgNaoPolitico(BigDecimal value) {
        this.vlContribPrevGeralAgNaoPolitico = value;
    }

     
    public BigDecimal getVlContribPrevProprioAgNaoPolitico() {
        return vlContribPrevProprioAgNaoPolitico;
    }

     
    public void setVlContribPrevProprioAgNaoPolitico(BigDecimal value) {
        this.vlContribPrevProprioAgNaoPolitico = value;
    }

}
