//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 04:21:25 PM BRST 
//


package br.gov.model.resumoFolha;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResumoFolhaPagamento", namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", propOrder = {
    "descritor",
    "listaResumoFolhaPagamento"
})

@XmlRootElement(name ="ResumoMensalFolhaPagamento")
public class ResumoFolhaPagamentoT {

    @XmlElement(name = "Descritor", required = true)
    protected DescritorMensalT descritor;
    @XmlElement(name = "ListaResumoFolhaPagamento", required = true)
    protected List<ResumoFolhaT> listaResumoFolhaPagamento;

     
    public DescritorMensalT getDescritor() {
        return descritor;
    }

     
    public void setDescritor(DescritorMensalT value) {
        this.descritor = value;
    }

     
    public List<ResumoFolhaT> getListaResumoFolhaPagamento() {
        if (listaResumoFolhaPagamento == null) {
            listaResumoFolhaPagamento = new ArrayList<ResumoFolhaT>();
        }
        return this.listaResumoFolhaPagamento;
    }

}
