//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:34:37 PM BRT 
//


package br.gov.model.auxiliares2017;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.model.auxiliares2017 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.model.auxiliares2017
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LegislacaoT }
     * 
     */
    public LegislacaoT createLegislacaoT() {
        return new LegislacaoT();
    }

    /**
     * Create an instance of {@link LegislacaoMunicipalT }
     * 
     */
    public LegislacaoMunicipalT createLegislacaoMunicipalT() {
        return new LegislacaoMunicipalT();
    }

    /**
     * Create an instance of {@link DespesaComLicitacaoT }
     * 
     */
    public DespesaComLicitacaoT createDespesaComLicitacaoT() {
        return new DespesaComLicitacaoT();
    }

    /**
     * Create an instance of {@link LegislacaoMunicipalComDatasT }
     * 
     */
    public LegislacaoMunicipalComDatasT createLegislacaoMunicipalComDatasT() {
        return new LegislacaoMunicipalComDatasT();
    }

}
