//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:37 PM BRST 
//


package br.gov.model.generico2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Descritor_t", propOrder = {
    "anoExercicio",
    "tipoDocumento",
    "entidade",
    "municipio",
    "dataCriacaoXML"
})
@XmlSeeAlso({
    DescritorPlanejamentoAtualizacaoT.class,
    DescritorContabil13T.class,
    DescritorContabilT.class,
    DescritorContasAnuaisT.class,
    DescritorPPAT.class,
    DescritorQuadrimestreT.class,
    DescritorPlanejamentoT.class,
    DescritorContabil14T.class,
    DescritorMensalT.class
})
public class DescritorT {

    @XmlElement(name = "AnoExercicio")
    protected int anoExercicio;
    @XmlElement(name = "TipoDocumento", required = true)
    protected TipoDocumentoT tipoDocumento;
    @XmlElement(name = "Entidade")
    protected int entidade;
    @XmlElement(name = "Municipio", required = true)
    protected String municipio;
    @XmlElement(name = "DataCriacaoXML", required = true)
    protected XMLGregorianCalendar dataCriacaoXML;

     
    public int getAnoExercicio() {
        return anoExercicio;
    }

     
    public void setAnoExercicio(int value) {
        this.anoExercicio = value;
    }

     
    public TipoDocumentoT getTipoDocumento() {
        return tipoDocumento;
    }

     
    public void setTipoDocumento(TipoDocumentoT value) {
        this.tipoDocumento = value;
    }

     
    public int getEntidade() {
        return entidade;
    }

     
    public void setEntidade(int value) {
        this.entidade = value;
    }

     
    public String getMunicipio() {
        return municipio;
    }

     
    public void setMunicipio(String value) {
        this.municipio = value;
    }

     
    public XMLGregorianCalendar getDataCriacaoXML() {
        return dataCriacaoXML;
    }

     
    public void setDataCriacaoXML(XMLGregorianCalendar value) {
        this.dataCriacaoXML = value;
    }

}
