//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:37 PM BRST 
//


package br.gov.model.generico2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescritorContasAnuais_t", propOrder = {
    "anoReferencia"
})
@XmlSeeAlso({
    DescritorConciliacoesBancariasT.class
})
public class DescritorContasAnuaisT
    extends DescritorT
{

    @XmlElement(name = "AnoReferencia")
    protected int anoReferencia;

     
    public int getAnoReferencia() {
        return anoReferencia;
    }

     
    public void setAnoReferencia(int value) {
        this.anoReferencia = value;
    }

}
