//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:37 PM BRST 
//


package br.gov.model.generico2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Endereco_t", propOrder = {
    "logradouro",
    "bairro",
    "cidade",
    "uf",
    "cep"
})
public class EnderecoT {

    @XmlElement(name = "Logradouro", required = true)
    protected String logradouro;
    @XmlElement(name = "Bairro", required = true)
    protected String bairro;
    @XmlElement(name = "Cidade", required = true)
    protected String cidade;
    @XmlElement(name = "UF", required = true)
    protected UFT uf;
    @XmlElement(name = "CEP", required = true)
    protected String cep;

     
    public String getLogradouro() {
        return logradouro;
    }

     
    public void setLogradouro(String value) {
        this.logradouro = value;
    }

     
    public String getBairro() {
        return bairro;
    }

     
    public void setBairro(String value) {
        this.bairro = value;
    }

     
    public String getCidade() {
        return cidade;
    }

     
    public void setCidade(String value) {
        this.cidade = value;
    }

     
    public UFT getUF() {
        return uf;
    }

     
    public void setUF(UFT value) {
        this.uf = value;
    }

     
    public String getCEP() {
        return cep;
    }

     
    public void setCEP(String value) {
        this.cep = value;
    }

}
