//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:20 PM BRST 
//


package br.gov.model.generico2016;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificacaoAgentePublico_t", namespace = "http://www.tce.sp.gov.br/audesp/xml/atospessoal", propOrder = {
    "cpf",
    "nome",
    "municipioLotacao",
    "entidadeLotacao",
    "cargoPolitico",
    "funcaoGoverno",
    "estagiario",
    "codigoCargo",
    "codigoFuncao",
    "situacao",
    "regimeJuridico",
    "possuiAutorizRecebAcimaTeto",
    "numeroProcessoJudicial"
})
public class IdentificacaoAgentePublicoT {

    @XmlElement(name = "CPF", required = true)
    protected CPFT cpf;
    @XmlElement(name = "Nome", required = true)
    protected String nome;
    @XmlElement(name = "MunicipioLotacao", required = true)
    protected String municipioLotacao;
    @XmlElement(name = "EntidadeLotacao")
    protected int entidadeLotacao;
    @XmlElement(name = "CargoPolitico")
    protected short cargoPolitico;
    @XmlElement(name = "FuncaoGoverno", required = true)
    protected String funcaoGoverno;
    @XmlElement(name = "Estagiario")
    protected short estagiario;
    @XmlElement(name = "CodigoCargo")
    protected String codigoCargo;
    @XmlElement(name = "CodigoFuncao")
    protected String codigoFuncao;
    @XmlElement(name = "Situacao")
    protected short situacao;
    @XmlElement(name = "RegimeJuridico")
    protected short regimeJuridico;
    @XmlElement(name = "PossuiAutorizRecebAcimaTeto")
    protected short possuiAutorizRecebAcimaTeto;
    @XmlElement(name = "NumeroProcessoJudicial")
    protected String numeroProcessoJudicial;

     
    public CPFT getCPF() {
        return cpf;
    }

     
    public void setCPF(CPFT value) {
        this.cpf = value;
    }

     
    public String getNome() {
        return nome;
    }

     
    public void setNome(String value) {
        this.nome = value;
    }

     
    public String getMunicipioLotacao() {
        return municipioLotacao;
    }

     
    public void setMunicipioLotacao(String value) {
        this.municipioLotacao = value;
    }

     
    public int getEntidadeLotacao() {
        return entidadeLotacao;
    }

     
    public void setEntidadeLotacao(int value) {
        this.entidadeLotacao = value;
    }

     
    public short getCargoPolitico() {
        return cargoPolitico;
    }

     
    public void setCargoPolitico(short value) {
        this.cargoPolitico = value;
    }

     
    public String getFuncaoGoverno() {
        return funcaoGoverno;
    }

     
    public void setFuncaoGoverno(String value) {
        this.funcaoGoverno = value;
    }

     
    public short getEstagiario() {
        return estagiario;
    }

     
    public void setEstagiario(short value) {
        this.estagiario = value;
    }

     
    public String getCodigoCargo() {
        return codigoCargo;
    }

     
    public void setCodigoCargo(String value) {
        this.codigoCargo = value;
    }

     
    public String getCodigoFuncao() {
        return codigoFuncao;
    }

     
    public void setCodigoFuncao(String value) {
        this.codigoFuncao = value;
    }

     
    public short getSituacao() {
        return situacao;
    }

     
    public void setSituacao(short value) {
        this.situacao = value;
    }

     
    public short getRegimeJuridico() {
        return regimeJuridico;
    }

     
    public void setRegimeJuridico(short value) {
        this.regimeJuridico = value;
    }

     
    public short getPossuiAutorizRecebAcimaTeto() {
        return possuiAutorizRecebAcimaTeto;
    }

     
    public void setPossuiAutorizRecebAcimaTeto(short value) {
        this.possuiAutorizRecebAcimaTeto = value;
    }

     
    public String getNumeroProcessoJudicial() {
        return numeroProcessoJudicial;
    }

     
    public void setNumeroProcessoJudicial(String value) {
        this.numeroProcessoJudicial = value;
    }

}
