//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:23:37 PM BRST 
//


package br.gov.model.generico2016;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


 
@XmlType(name = "OperacaoPlanejamento_t")
@XmlEnum
public enum OperacaoPlanejamentoT {

    INCLUSAO,
    EXCLUSAO;

    public String value() {
        return name();
    }

    public static OperacaoPlanejamentoT fromValue(String v) {
        return valueOf(v);
    }

}
