//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 06:00:43 PM BRST 
//


package br.gov.model.folhaOrdinaria;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FolhaSuplementarAgentePublico_t", propOrder = {
    "descritor",
    "mesCompetencia",
    "dataPagamento",
    "identificacaoAgentePublico",
    "identificacaoPensionista"
})
public class FolhaSuplementarAgentePublicoT {

    @XmlElement(name = "Descritor", required = true)
    protected DescritorT descritor;
    @XmlElement(name = "MesCompetencia")
    protected int mesCompetencia;
    @XmlElement(name = "DataPagamento", required = true)
    protected XMLGregorianCalendar dataPagamento;
    @XmlElement(name = "IdentificacaoAgentePublico", required = true)
    protected List<IdentificacaoAgentePublicoExtT> identificacaoAgentePublico;
    @XmlElement(name = "IdentificacaoPensionista")
    protected List<IdentificacaoPensionistaExtT> identificacaoPensionista;

     
    public DescritorT getDescritor() {
        return descritor;
    }

     
    public void setDescritor(DescritorT value) {
        this.descritor = value;
    }

     
    public int getMesCompetencia() {
        return mesCompetencia;
    }

     
    public void setMesCompetencia(int value) {
        this.mesCompetencia = value;
    }

     
    public XMLGregorianCalendar getDataPagamento() {
        return dataPagamento;
    }

     
    public void setDataPagamento(XMLGregorianCalendar value) {
        this.dataPagamento = value;
    }

     
    public List<IdentificacaoAgentePublicoExtT> getIdentificacaoAgentePublico() {
        if (identificacaoAgentePublico == null) {
            identificacaoAgentePublico = new ArrayList<IdentificacaoAgentePublicoExtT>();
        }
        return this.identificacaoAgentePublico;
    }

     
    public List<IdentificacaoPensionistaExtT> getIdentificacaoPensionista() {
        if (identificacaoPensionista == null) {
            identificacaoPensionista = new ArrayList<IdentificacaoPensionistaExtT>();
        }
        return this.identificacaoPensionista;
    }

}
