//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 05:00:15 PM BRST 
//


package br.gov.model.folhaOrdinaria;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificacaoAgentePublico_t1",  propOrder = {
    "cpf",
    "municipioLotacao",
    "entidadeLotacao",
    "codigoCargo",
    "codigoFuncao",
    "formaPagamento",
    "numeroBanco",
    "agencia",
    "contaCorrente",
    "valores"
})
public class IdentificacaoAgentePublicoT1 {

    @XmlElement(name = "CPF", required = true)
    protected CPFT cpf;
    @XmlElement(name = "MunicipioLotacao", required = true)
    protected String municipioLotacao;
    @XmlElement(name = "EntidadeLotacao")
    protected int entidadeLotacao;
    @XmlElement(name = "CodigoCargo")
    protected String codigoCargo;
    @XmlElement(name = "CodigoFuncao")
    protected String codigoFuncao;
    protected short formaPagamento;
    protected String numeroBanco;
    protected String agencia;
    @XmlElement(name = "ContaCorrente")
    protected String contaCorrente;
    @XmlElement(name = "Valores", required = true)
    protected IdentificacaoAgentePublicoT1 .Valores valores;

     
    public CPFT getCPF() {
        return cpf;
    }

     
    public void setCPF(CPFT value) {
        this.cpf = value;
    }

     
    public String getMunicipioLotacao() {
        return municipioLotacao;
    }

     
    public void setMunicipioLotacao(String value) {
        this.municipioLotacao = value;
    }

     
    public int getEntidadeLotacao() {
        return entidadeLotacao;
    }

     
    public void setEntidadeLotacao(int value) {
        this.entidadeLotacao = value;
    }

     
    public String getCodigoCargo() {
        return codigoCargo;
    }

     
    public void setCodigoCargo(String value) {
        this.codigoCargo = value;
    }

     
    public String getCodigoFuncao() {
        return codigoFuncao;
    }

     
    public void setCodigoFuncao(String value) {
        this.codigoFuncao = value;
    }

     
    public short getFormaPagamento() {
        return formaPagamento;
    }

     
    public void setFormaPagamento(short value) {
        this.formaPagamento = value;
    }

     
    public String getNumeroBanco() {
        return numeroBanco;
    }

     
    public void setNumeroBanco(String value) {
        this.numeroBanco = value;
    }

     
    public String getAgencia() {
        return agencia;
    }

     
    public void setAgencia(String value) {
        this.agencia = value;
    }

     
    public String getContaCorrente() {
        return contaCorrente;
    }

     
    public void setContaCorrente(String value) {
        this.contaCorrente = value;
    }

     
    public IdentificacaoAgentePublicoT1 .Valores getValores() {
        return valores;
    }

     
    public void setValores(IdentificacaoAgentePublicoT1 .Valores value) {
        this.valores = value;
    }


     
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valorPagoContaCorrente",
        "valorPagoOutrasFormas"
    })
    public static class Valores {

        @XmlElement(namespace = "", required = true)
        protected BigDecimal valorPagoContaCorrente;
        @XmlElement(namespace = "", required = true)
        protected BigDecimal valorPagoOutrasFormas;

         
        public BigDecimal getValorPagoContaCorrente() {
            return valorPagoContaCorrente;
        }

         
        public void setValorPagoContaCorrente(BigDecimal value) {
            this.valorPagoContaCorrente = value;
        }

         
        public BigDecimal getValorPagoOutrasFormas() {
            return valorPagoOutrasFormas;
        }

         
        public void setValorPagoOutrasFormas(BigDecimal value) {
            this.valorPagoOutrasFormas = value;
        }

    }

}
