//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 03:57:18 PM BRT 
//



@XmlSchema(namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@XmlNs(prefix = "ap", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/atospessoal"),
		@XmlNs(prefix = "aux", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/auxiliar"),
		@XmlNs(prefix = "foap", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/remuneracao"),
		@XmlNs(prefix = "gen", namespaceURI = "http://www.tce.sp.gov.br/audesp/xml/generico")

})

package br.gov.model.folhaOrdinaria;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;


