//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 05:00:15 PM BRST 
//


package br.gov.model.folhaOrdinaria;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagamentoFolhaOrdinariaAgentePublico_t",  propOrder = {
    "descritor",
    "mesCompetencia",
    "anoPagamento",
    "mesPagamento"
})
@XmlRootElement(name = "PagamentoFolhaOrdinariaAgentePublicoT")
public class PagamentoFolhaOrdinariaAgentePublicoT {

    @XmlElement(name = "Descritor", required = true)
    protected DescritorT descritor;
    @XmlElement(name = "MesCompetencia")
    protected int mesCompetencia;
    @XmlElement(name = "AnoPagamento")
    protected int anoPagamento;
    @XmlElement(name = "MesPagamento")
    protected int mesPagamento;

     
    public DescritorT getDescritor() {
        return descritor;
    }

     
    public void setDescritor(DescritorT value) {
        this.descritor = value;
    }

     
    public int getMesCompetencia() {
        return mesCompetencia;
    }

     
    public void setMesCompetencia(int value) {
        this.mesCompetencia = value;
    }

     
    public int getAnoPagamento() {
        return anoPagamento;
    }

     
    public void setAnoPagamento(int value) {
        this.anoPagamento = value;
    }

     
    public int getMesPagamento() {
        return mesPagamento;
    }

     
    public void setMesPagamento(int value) {
        this.mesPagamento = value;
    }

}
