//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:43:01 PM BRT 
//


package br.gov.model.generico2017;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescritorPlanejamento_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescritorPlanejamento_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tce.sp.gov.br/audesp/xml/generico}Descritor_t">
 *       &lt;sequence>
 *         &lt;element name="CicloOrcamento" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CicloOrcamento_t"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescritorPlanejamento_t", propOrder = {
    "cicloOrcamento"
})
public class DescritorPlanejamentoT
    extends DescritorT
{

    @XmlElement(name = "CicloOrcamento", required = true)
    protected String cicloOrcamento;

    /**
     * Gets the value of the cicloOrcamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCicloOrcamento() {
        return cicloOrcamento;
    }

    /**
     * Sets the value of the cicloOrcamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCicloOrcamento(String value) {
        this.cicloOrcamento = value;
    }

}
