//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:43:01 PM BRT 
//


package br.gov.model.generico2017;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntidadeOrcamentaria_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntidadeOrcamentaria_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Orgao" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoEntidade_t"/>
 *         &lt;element name="UO" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoEntidadeContabil_t"/>
 *         &lt;element name="UE" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoEntidadeContabil_t"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntidadeOrcamentaria_t", propOrder = {
    "orgao",
    "uo",
    "ue"
})
public class EntidadeOrcamentariaT {

    @XmlElement(name = "Orgao")
    protected int orgao;
    @XmlElement(name = "UO")
    protected int uo;
    @XmlElement(name = "UE")
    protected int ue;

    /**
     * Gets the value of the orgao property.
     * 
     */
    public int getOrgao() {
        return orgao;
    }

    /**
     * Sets the value of the orgao property.
     * 
     */
    public void setOrgao(int value) {
        this.orgao = value;
    }

    /**
     * Gets the value of the uo property.
     * 
     */
    public int getUO() {
        return uo;
    }

    /**
     * Sets the value of the uo property.
     * 
     */
    public void setUO(int value) {
        this.uo = value;
    }

    /**
     * Gets the value of the ue property.
     * 
     */
    public int getUE() {
        return ue;
    }

    /**
     * Sets the value of the ue property.
     * 
     */
    public void setUE(int value) {
        this.ue = value;
    }

}
