//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:43:01 PM BRT 
//


package br.gov.model.generico2017;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LegislacaoMunicipalComDatas_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegislacaoMunicipalComDatas_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tce.sp.gov.br/audesp/xml/auxiliar}LegislacaoMunicipal_t">
 *       &lt;sequence>
 *         &lt;element name="DataPublicacao" type="{http://www.tce.sp.gov.br/audesp/xml/auxiliar}DataLei_t"/>
 *         &lt;element name="DataVigencia" type="{http://www.tce.sp.gov.br/audesp/xml/auxiliar}DataLei_t"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegislacaoMunicipalComDatas_t", namespace = "http://www.tce.sp.gov.br/audesp/xml/auxiliar", propOrder = {
    "dataPublicacao",
    "dataVigencia"
})
public class LegislacaoMunicipalComDatasT
    extends LegislacaoMunicipalT
{

    @XmlElement(name = "DataPublicacao", required = true)
    protected XMLGregorianCalendar dataPublicacao;
    @XmlElement(name = "DataVigencia", required = true)
    protected XMLGregorianCalendar dataVigencia;

    /**
     * Gets the value of the dataPublicacao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataPublicacao() {
        return dataPublicacao;
    }

    /**
     * Sets the value of the dataPublicacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataPublicacao(XMLGregorianCalendar value) {
        this.dataPublicacao = value;
    }

    /**
     * Gets the value of the dataVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataVigencia() {
        return dataVigencia;
    }

    /**
     * Sets the value of the dataVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataVigencia(XMLGregorianCalendar value) {
        this.dataVigencia = value;
    }

}
