//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:43:01 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tce.sp.gov.br/audesp/xml/generico", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.gov.model.generico2017;
