//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:30:46 PM BRT 
//


package br.gov.bean.verbasRemuneratorias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcaoGoverno_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcaoGoverno_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroAcao" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoAcao_t"/>
 *         &lt;element name="TipoAcao" type="{http://www.tce.sp.gov.br/audesp/xml/generico}TipoAcao_t"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcaoGoverno_t", propOrder = {
    "numeroAcao",
    "tipoAcao"
})
public class AcaoGovernoT {

    @XmlElement(name = "NumeroAcao")
    protected int numeroAcao;
    @XmlElement(name = "TipoAcao", required = true)
    protected String tipoAcao;

    /**
     * Gets the value of the numeroAcao property.
     * 
     */
    public int getNumeroAcao() {
        return numeroAcao;
    }

    /**
     * Sets the value of the numeroAcao property.
     * 
     */
    public void setNumeroAcao(int value) {
        this.numeroAcao = value;
    }

    /**
     * Gets the value of the tipoAcao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAcao() {
        return tipoAcao;
    }

    /**
     * Sets the value of the tipoAcao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAcao(String value) {
        this.tipoAcao = value;
    }

}
