//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:30:46 PM BRT 
//


package br.gov.bean.verbasRemuneratorias;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CadastroVerbasRemuneratorias_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CadastroVerbasRemuneratorias_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Descritor" type="{http://www.tce.sp.gov.br/audesp/xml/generico}Descritor_t"/>
 *         &lt;element name="VerbasRemuneratorias" type="{http://www.tce.sp.gov.br/audesp/xml/remuneracao}VerbasRemuneratorias_t" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CadastroVerbasRemuneratorias_t", namespace = "http://www.tce.sp.gov.br/audesp/xml/remuneracao", propOrder = {
    "descritor",
    "verbasRemuneratorias"
})
public class CadastroVerbasRemuneratoriasT {

    @XmlElement(name = "Descritor", required = true)
    protected DescritorT descritor;
    @XmlElement(name = "VerbasRemuneratorias", required = true)
    protected List<VerbasRemuneratoriasT> verbasRemuneratorias;

    /**
     * Gets the value of the descritor property.
     * 
     * @return
     *     possible object is
     *     {@link DescritorT }
     *     
     */
    public DescritorT getDescritor() {
        return descritor;
    }

    /**
     * Sets the value of the descritor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescritorT }
     *     
     */
    public void setDescritor(DescritorT value) {
        this.descritor = value;
    }

    /**
     * Gets the value of the verbasRemuneratorias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verbasRemuneratorias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVerbasRemuneratorias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerbasRemuneratoriasT }
     * 
     * 
     */
    public List<VerbasRemuneratoriasT> getVerbasRemuneratorias() {
        if (verbasRemuneratorias == null) {
            verbasRemuneratorias = new ArrayList<VerbasRemuneratoriasT>();
        }
        return this.verbasRemuneratorias;
    }

}
