//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:30:46 PM BRT 
//


package br.gov.bean.verbasRemuneratorias;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContaCorrenteBancaria_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContaCorrenteBancaria_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Banco" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoBanco_t"/>
 *         &lt;element name="Agencia" type="{http://www.tce.sp.gov.br/audesp/xml/generico}CodigoAgenciaBancaria_t"/>
 *         &lt;element name="DVAgencia" type="{http://www.tce.sp.gov.br/audesp/xml/generico}DigitoVerificador_t" minOccurs="0"/>
 *         &lt;element name="ContaCorrente" type="{http://www.tce.sp.gov.br/audesp/xml/generico}NumeroContaCorrenteBancaria_t"/>
 *         &lt;element name="DVContaCorrente" type="{http://www.tce.sp.gov.br/audesp/xml/generico}DigitoVerificador_t" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContaCorrenteBancaria_t", propOrder = {
    "banco",
    "agencia",
    "dvAgencia",
    "contaCorrente",
    "dvContaCorrente"
})
public class ContaCorrenteBancariaT {

    @XmlElement(name = "Banco", required = true)
    protected String banco;
    @XmlElement(name = "Agencia", required = true)
    protected String agencia;
    @XmlElement(name = "DVAgencia")
    protected String dvAgencia;
    @XmlElement(name = "ContaCorrente", required = true)
    protected String contaCorrente;
    @XmlElement(name = "DVContaCorrente")
    protected String dvContaCorrente;

    /**
     * Gets the value of the banco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBanco() {
        return banco;
    }

    /**
     * Sets the value of the banco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBanco(String value) {
        this.banco = value;
    }

    /**
     * Gets the value of the agencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencia() {
        return agencia;
    }

    /**
     * Sets the value of the agencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencia(String value) {
        this.agencia = value;
    }

    /**
     * Gets the value of the dvAgencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDVAgencia() {
        return dvAgencia;
    }

    /**
     * Sets the value of the dvAgencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDVAgencia(String value) {
        this.dvAgencia = value;
    }

    /**
     * Gets the value of the contaCorrente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContaCorrente() {
        return contaCorrente;
    }

    /**
     * Sets the value of the contaCorrente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContaCorrente(String value) {
        this.contaCorrente = value;
    }

    /**
     * Gets the value of the dvContaCorrente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDVContaCorrente() {
        return dvContaCorrente;
    }

    /**
     * Sets the value of the dvContaCorrente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDVContaCorrente(String value) {
        this.dvContaCorrente = value;
    }

}
