//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.13 at 05:30:46 PM BRT 
//


package br.gov.bean.verbasRemuneratorias;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeclaracaoNegativa_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeclaracaoNegativa_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Nenhum dado a declarar"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeclaracaoNegativa_t")
@XmlEnum
public enum DeclaracaoNegativaT {

    @XmlEnumValue("Nenhum dado a declarar")
    NENHUM_DADO_A_DECLARAR("Nenhum dado a declarar");
    private final String value;

    DeclaracaoNegativaT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeclaracaoNegativaT fromValue(String v) {
        for (DeclaracaoNegativaT c: DeclaracaoNegativaT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
