//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:30:58 PM BRST 
//


package br.gov.model.auxiliares2016;

import javax.xml.bind.annotation.XmlRegistry;


 
@XmlRegistry
public class ObjectFactory {


     
    public ObjectFactory() {
    }

     
    public LegislacaoMunicipalT createLegislacaoMunicipalT() {
        return new LegislacaoMunicipalT();
    }

     
    public DespesaComLicitacaoT createDespesaComLicitacaoT() {
        return new DespesaComLicitacaoT();
    }

     
    public LegislacaoT createLegislacaoT() {
        return new LegislacaoT();
    }

     
    public LegislacaoMunicipalComDatasT createLegislacaoMunicipalComDatasT() {
        return new LegislacaoMunicipalComDatasT();
    }

}
